import type { SimOptions } from '@wow-simc/shared';
import { OUTPUT_PATH_PLACEHOLDER } from './quick-sim.js';
import { fixSimcInput } from './fix-simc-input.js';

export interface DroptimzerItem {
  id: number
  name: string
  slot: string
  item_level: number
  bonus_ids?: number[]
  boss_name: string
}

/**
 * Build a complete SimC profile for a Droptimizer simulation.
 *
 * Creates one profileset per loot item, swapping it into its slot to measure
 * the DPS impact relative to the base character.
 *
 * @param simcInput  Raw /simc addon export string (base character).
 * @param items      List of loot items to evaluate.
 * @param options    Simulation options.
 * @returns          Full .simc file content as a string.
 */
export function buildDroptimizerProfile(
  simcInput: string,
  items: DroptimzerItem[],
  options: SimOptions,
): string {
  const lines: string[] = [
    '# Droptimizer - generated by wow-simc-web',
    '',
    fixSimcInput(simcInput.trim()),
    '',
    '# Output',
    `json2=${OUTPUT_PATH_PLACEHOLDER}`,
    '',
    '# Simulation options',
    `iterations=${options.iterations}`,
    `fight_style=${options.fight_style}`,
    `max_time=${options.fight_length}`,
    `target_error=${options.target_error}`,
    `threads=${options.threads}`,
    `desired_targets=${options.targets}`,
    'item_verification=0',
    'profileset_work_threads=1',
    '',
    '# Droptimizer profilesets',
  ];

  for (const item of items) {
    // Skip items with invalid item level — SimC rejects ilevel=0
    if (!item.item_level || item.item_level <= 0) continue;

    const safeName = `${item.boss_name} - ${item.name} (${item.item_level})`
      .replace(/"/g, "'");

    let itemLine = `${item.slot}=,id=${item.id},ilevel=${item.item_level}`;
    if (item.bonus_ids && item.bonus_ids.length > 0) {
      itemLine += `,bonus_id=${item.bonus_ids.join('/')}`;
    }

    lines.push(`profileset."${safeName}"+=${itemLine}`);
  }

  return lines.join('\n');
}
