import type { SimOptions } from '@wow-simc/shared';
import { OUTPUT_PATH_PLACEHOLDER } from './quick-sim.js';
import { fixSimcInput } from './fix-simc-input.js';

const GEAR_SLOTS = [
  'head', 'neck', 'shoulders', 'back', 'chest', 'wrists',
  'hands', 'waist', 'legs', 'feet', 'finger1', 'finger2',
  'trinket1', 'trinket2', 'main_hand', 'off_hand',
];

/**
 * Build a complete SimC profile for a Gear Compare simulation.
 *
 * Uses Profile A as the base character, then adds Profile B as a profileset
 * by extracting gear slot lines from the B simc string and overriding them.
 *
 * @param simcInputA  Raw /simc string for Set A (base).
 * @param simcInputB  Raw /simc string for Set B (alternate gear).
 * @param nameA       Display name for Set A.
 * @param nameB       Display name for Set B.
 * @param options     Simulation options.
 * @returns           Full .simc file content as a string.
 */
export function buildGearCompareProfile(
  simcInputA: string,
  simcInputB: string,
  nameA: string,
  nameB: string,
  options: SimOptions,
): string {
  const safeNameA = nameA.replace(/"/g, "'");
  const safeNameB = nameB.replace(/"/g, "'");

  const lines: string[] = [
    '# Gear Compare - generated by wow-simc-web',
    `# Set A: ${safeNameA}  |  Set B: ${safeNameB}`,
    '',
    fixSimcInput(simcInputA.trim()),
    '',
    '# Output',
    `json2=${OUTPUT_PATH_PLACEHOLDER}`,
    '',
    '# Simulation options',
    `iterations=${options.iterations}`,
    `fight_style=${options.fight_style}`,
    `max_time=${options.fight_length}`,
    `target_error=${options.target_error}`,
    `threads=${options.threads}`,
    `desired_targets=${options.targets}`,
    'item_verification=0',
    '',
    `# --- Set B: ${safeNameB} ---`,
  ];

  // Extract gear slot lines from simcInputB and emit as profileset overrides
  const bLines = simcInputB.split(/\r?\n/);
  let hasGearLines = false;

  for (const line of bLines) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const eqIdx = trimmed.indexOf('=');
    if (eqIdx === -1) continue;
    const key = trimmed.slice(0, eqIdx).toLowerCase();
    if (GEAR_SLOTS.includes(key)) {
      lines.push(`profileset."${safeNameB}"+=${trimmed}`);
      hasGearLines = true;
    }
  }

  // Fallback: if no gear lines found, still emit an empty profileset
  // so SimC can at least run the base profile as "Set B" (same as A)
  if (!hasGearLines) {
    lines.push(`profileset."${safeNameB}"+=`);
  }

  return lines.join('\n');
}
