import type { SimOptions } from '@wow-simc/shared';
import { fixSimcInput } from './fix-simc-input.js';

/**
 * Placeholder replaced by the runner with the actual temp json output path.
 */
export const OUTPUT_PATH_PLACEHOLDER = '{{OUTPUT_PATH}}';

/**
 * Build a complete SimulationCraft .simc file content for a quick single-character sim.
 *
 * Takes the raw /simc addon string as-is, then appends the standard output
 * and simulation option directives. The json2 output path uses a placeholder
 * (`{{OUTPUT_PATH}}`) that the runner will replace before writing the temp file.
 *
 * @param simcInput  Raw SimC addon export string.
 * @param options    Simulation options (iterations, fight style, etc.).
 * @returns          Full .simc file content as a string.
 */
export function buildQuickSimProfile(
  simcInput: string,
  options: SimOptions,
): string {
  const lines: string[] = [
    '# Quick Sim - generated by wow-simc-web',
    '',
    fixSimcInput(simcInput.trim()),
    '',
    '# Output',
    `json2=${OUTPUT_PATH_PLACEHOLDER}`,
    '',
    '# Simulation options',
    `iterations=${options.iterations}`,
    `fight_style=${options.fight_style}`,
    `max_time=${options.fight_length}`,
    `target_error=${options.target_error}`,
    `threads=${options.threads}`,
    `desired_targets=${options.targets}`,
    'item_verification=0',
  ];

  return lines.join('\n');
}
