import type { SimOptions } from '@wow-simc/shared';
import { fixSimcInput } from './fix-simc-input.js';
import { OUTPUT_PATH_PLACEHOLDER } from './quick-sim.js';

/**
 * Stats for which SimC will calculate scale factors.
 * Covers the primary and secondary stats relevant across all specs.
 */
const SCALE_STATS = [
  'strength',
  'intellect',
  'agility',
  'crit_rating',
  'haste_rating',
  'mastery_rating',
  'versatility_rating',
].join(',');

/**
 * Build a complete SimulationCraft .simc file content for a stat weights sim.
 *
 * Appends `calculate_scale_factors=1` and `scale_only=<stats>` to the base
 * SimC input string, along with standard output and simulation options.
 *
 * @param simcInput  Raw SimC addon export string.
 * @param options    Simulation options.
 * @returns          Full .simc file content as a string.
 */
export function buildStatWeightsProfile(
  simcInput: string,
  options: SimOptions,
): string {
  const lines: string[] = [
    '# Stat Weights - generated by wow-simc-web',
    '',
    fixSimcInput(simcInput.trim()),
    '',
    '# Output',
    `json2=${OUTPUT_PATH_PLACEHOLDER}`,
    '',
    '# Simulation options',
    `iterations=${options.iterations}`,
    `fight_style=${options.fight_style}`,
    `max_time=${options.fight_length}`,
    `target_error=${options.target_error}`,
    `threads=${options.threads}`,
    `desired_targets=${options.targets}`,
    'item_verification=0',
    '',
    '# Scale factors',
    'calculate_scale_factors=1',
    `scale_only=${SCALE_STATS}`,
  ];

  return lines.join('\n');
}
