import type { Character, GearItem, SimOptions } from '@wow-simc/shared';
import { OUTPUT_PATH_PLACEHOLDER } from './quick-sim.js';
import { fixSimcInput } from './fix-simc-input.js';

/**
 * Maximum number of profilesets SimC can reliably handle in a single run.
 * Exceeding this can cause excessive memory usage and run time.
 */
export const MAX_PROFILESETS = 800;

/**
 * Build a profileset entry line for a single gear item.
 *
 * Example output:
 *   profileset."head_item_123456_639"+=head=,id=123456,bonus_id=1234/5678,ilevel=639
 */
function buildProfilesetLine(
  profilesetName: string,
  slot: string,
  item: GearItem,
): string {
  const parts: string[] = [`id=${item.id}`];

  if (item.bonus_ids && item.bonus_ids.length > 0) {
    parts.push(`bonus_id=${item.bonus_ids.join('/')}`);
  }

  // Only set ilevel if we have a valid one — SimC can resolve from bonus_id otherwise
  if (item.item_level && item.item_level > 0) {
    parts.push(`ilevel=${item.item_level}`);
  }

  if (item.enchant_id) {
    parts.push(`enchant_id=${item.enchant_id}`);
  }

  if (item.gem_ids && item.gem_ids.length > 0) {
    parts.push(`gem_id=${item.gem_ids.join('/')}`);
  }

  const itemStr = `,${parts.join(',')}`;
  return `profileset."${profilesetName}"+=${slot}=${itemStr}`;
}

/**
 * Sanitize a string for use in a SimC profileset name.
 * Removes characters that SimC doesn't handle well in profile names.
 */
function sanitizeName(name: string): string {
  return name.replace(/[^a-zA-Z0-9_\-]/g, '_').replace(/_+/g, '_');
}

/**
 * Build a complete SimulationCraft .simc file content for a top-gear profileset sim.
 *
 * Uses the character's `simc_string` as the base profile, then appends one
 * profileset entry per candidate item per slot. The total number of profilesets
 * is capped at MAX_PROFILESETS (800) to avoid excessive run times.
 *
 * @param character   The character whose `simc_string` is used as the base.
 * @param candidates  Map of slot -> array of candidate GearItems to compare.
 * @param options     Simulation options.
 * @returns           Full .simc file content as a string.
 */
export function buildTopGearProfile(
  character: Character,
  candidates: Record<string, GearItem[]>,
  options: SimOptions,
): string {
  const lines: string[] = [
    '# Top Gear - generated by wow-simc-web',
    '',
    fixSimcInput(character.simc_string.trim()),
    '',
    '# Output',
    `json2=${OUTPUT_PATH_PLACEHOLDER}`,
    '',
    '# Simulation options',
    `iterations=${options.iterations}`,
    `fight_style=${options.fight_style}`,
    `max_time=${options.fight_length}`,
    `target_error=${options.target_error}`,
    `threads=${options.threads}`,
    `desired_targets=${options.targets}`,
    'item_verification=0',
    '',
    '# Profilesets',
  ];

  let profilesetCount = 0;

  outer: for (const [slot, items] of Object.entries(candidates)) {
    for (const item of items) {
      // Skip items with invalid item level — unless they have bonus_ids (SimC can resolve ilvl from bonus data)
      if ((!item.item_level || item.item_level <= 0) && (!item.bonus_ids || item.bonus_ids.length === 0)) continue;

      if (profilesetCount >= MAX_PROFILESETS) {
        lines.push(
          `# WARNING: MAX_PROFILESETS (${MAX_PROFILESETS}) reached - remaining candidates omitted`,
        );
        break outer;
      }

      const safeName = sanitizeName(item.name || `item_${item.id}`);
      const profilesetName = `${slot}_${safeName}_${item.item_level}`;

      lines.push(buildProfilesetLine(profilesetName, slot, item));
      profilesetCount++;
    }
  }

  return lines.join('\n');
}
